#
# Copyright (c) 2019-2026 0xACE8
#
# 本ソフトウェアはフリーソフトウェアであり、MITライセンスの下で公開されています。
# 詳細については /LICENSE を参照してください。
#
# https://github.com/0xACE8
#
# 説明: GitHub Actionsのモジュール化を活用し、プライバシーとセキュリティを確保したOpenWrtビルド。
#

name: Build raspberry-pi_3b imwrt 25.12ss kernel 6.12.x actions.

on:
  workflow_dispatch:
    inputs:
      restore_config:
        description: 'Restore Configuration. 🇯🇵 設定を復元'
        type: boolean
        default: true
      upload_firmware:
        description: 'Upload FW to Artifact. 🇯🇵 Artifactに保存'
        type: boolean
        default: false
      upload_release:
        description: 'Upload FW to Release.. 🇯🇵 Releaseに公開'
        type: boolean
        default: true
      telegram_notify:
        description: 'Telegram Notification. 🇯🇵 Telegram通知'
        type: boolean
        default: true
      keepalive_cache:
        description: 'Manual Cache Keepalive 🇯🇵 保活モード'
        type: boolean
        default: false
      clean_cache:
        description: 'Clean all old CACHE... 🇯🇵 CACHEを削除'
        required: false
        type: boolean
        default: false
  schedule:
    - cron: '0 2 * * 0'
    - cron: '0 0 1 * *'
    
env:
  # annawrt 2410
  REPO_IMMORTALWRT_SOURCE_LINK:         ${{ secrets.REPO_IMMORTALWRT_SOURCE_LINK }}
  REPO_IMMORTALWRT_2410SS_TREE:         ${{ secrets.REPO_IMMORTALWRT_2410SS_TREE }}
  REPO_IMMORTALWRT_2512SS_HEAD:         ${{ secrets.REPO_IMMORTALWRT_2512SS_HEAD }}
  REPO_IMMORTALWRT_2410SS_DIFF:         ${{ secrets.REPO_IMMORTALWRT_2410SS_DIFF }}
  # cmcc_xr30-emmc
  RASPBERRYPI_3B_IMWRT2410SS_PATCHES:   ${{ secrets.RASPBERRYPI_3B_IMWRT2410SS_PATCHES }}
  RASPBERRYPI_3B_IMWRT2512SS_PROFILE:   ${{ secrets.RASPBERRYPI_3B_IMWRT2512SS_PROFILE }}
  RASPBERRYPI_3B_IMWRT2410SS_ARCHIVE:   ${{ secrets.RASPBERRYPI_3B_IMWRT2410SS_ARCHIVE }}
  # token
  GITHUB_TOKEN:                         ${{ secrets.ACCESS_TOKEN }}
  ACCESS_TOKEN:                         ${{ secrets.ACCESS_TOKEN }}
  # feeds source & check sha512sum
  ADD_FEEDS_OP2512:                     ${{ secrets.ADD_FEEDS_OP2512 }}
  ACCESS_SHA512SUM:                     ${{ secrets.ACCESS_SHA512SUM }}
  ACCESS_REPACKAGE:                     ${{ secrets.ACCESS_REPACKAGE }}
  # luci & packages repo
  PLUGIN_REPO_SLUG:                     ${{ secrets.PLUGIN_REPO_SLUG }}
  PLUGIN_REPO_HEAD:                     ${{ secrets.PLUGIN_REPO_HEAD }}
  PLUGIN_REPO_FLOW:                     ${{ secrets.PLUGIN_REPO_FLOW }}
  # cmcc color sytle for argon
  ARGON_THEME_RPI:                      ${{ secrets.ARGON_THEME_RPI }}
  # telegram bot
  TELEGRAM_BOT_KEY:                     ${{ secrets.TELEGRAM_BOT_KEY }}
  TELEGRAM_CHAT_ID:                     ${{ secrets.TELEGRAM_CHAT_ID }}
  # input status
  INPUT_RESTORE:                        ${{ github.event.inputs.restore_config }}
  INPUT_ARTIFACT:                       ${{ github.event.inputs.upload_firmware }}
  INPUT_RELEASE:                        ${{ github.event.inputs.upload_release }}
  INPUT_NOTIFY:                         ${{ github.event.inputs.telegram_notify }}
  INPUT_CLEANCACHE:                     ${{ github.event.inputs.clean_cache }}
  IS_KEEPALIVE:                         ${{ github.event_name == 'schedule' || github.event.inputs.keepalive_cache == 'true' }}
  # hardware & repo info
  DEVICE_NAME:                          Raspberry-Pi_3B
  TARGET_CHIP:                          bcm2710
  TARGET_DISK:                          8G_TF
  SOURCE_CODE:                          immortalwrt
  KERNEL_VERS:                          kernel_6.12
  OUTPUT_FILE:                          diamondwrt-25.12rc4-k6.12-bcm2710-raspberry-pi_3b-sysupgrade
  TZ: "Asia/Tokyo"

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions: write-all

    steps:
    - name: Start Timer (計測開始)
      run: |
        echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
        echo "CACHE_MONTH=$(date +%Y%m)" >> $GITHUB_ENV

    - name: Sync and Wait for Plugin Repo (プラグインリポジトリの同期と待機)
      run: |
        LAST_TS=$(date -d $(gh run list -w "$PLUGIN_REPO_FLOW" -R "$PLUGIN_REPO_SLUG" -s success --limit 1 --json updatedAt -q '.[0].updatedAt // "1970-01-01"') +%s)
        DIFF=$(( ($(date +%s) - LAST_TS) / 3600 ))

        if [ "$DIFF" -ge 24 ]; then
          echo "⚠️ 最終同期から ${DIFF}時間経過。同期を開始します..."
          gh workflow run "$PLUGIN_REPO_FLOW" -R "$PLUGIN_REPO_SLUG" -r "$PLUGIN_REPO_HEAD"
          
          for i in {1..30}; do
            sleep 20
            RUN_ID=$(gh run list -w "$PLUGIN_REPO_FLOW" -R "$PLUGIN_REPO_SLUG" --limit 1 --json databaseId,status -q 'map(select(.status != "completed")) | .[0].databaseId')
            [[ -n "$RUN_ID" && "$RUN_ID" != "null" ]] && break
          done

          [[ -z "$RUN_ID" ]] && echo "❌ Timeout" && exit 1
          gh run watch "$RUN_ID" -R "$PLUGIN_REPO_SLUG" --exit-status
        else
          echo "✅ 最近同期されました（${DIFF}時間前）。スキップします。"
        fi

    - name: Checkout (チェックアウト)
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Delete Old Workflows (古いワークフローの削除)
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
        delete_workflow_pattern: "25.12ss kernel 6.12.x"

    - name: Clean Up All Old Caches (全ての旧キャッシュを削除)
      if: |
        github.event.inputs.clean_cache == 'true' || 
        github.event.schedule == '0 0 1 * *'
      shell: bash
      run: |
        KEYS=("${{ runner.os }}-openwrt-dl-v3-" "MT7981b-[${{ env.CACHE_MONTH }}]")
        for KEY in "${KEYS[@]}"; do
          CACHES=$(gh cache list -R ${{ github.repository }} --limit 100 --json key -q ".[].key" 2>/dev/null | grep -F "$KEY" || true)
          for cache_key in $CACHES; do
            gh cache delete "$cache_key" -R ${{ github.repository }} || true
          done
        done
        echo "✨ すべてのクリーンアップ処理が完了しました！"

    - name: Check Server Performance (サーバー性能の確認)
      id: check_env
      run: |
        CPU_MODEL=$(cat /proc/cpuinfo | grep -m1 "model name" | awk -F: '{print $2}' | sed 's/^[ \t]*//')
        FREE_SPACE=$(df --block-size=1G / | awk 'NR==2 {print $4}')
        echo "⚠️注意⚠️"
        echo "サーバーのリソースは有限です。プラグインの過剰な選択はCPU高負荷の原因となります。"
        echo -e "既知のCPUモデル（降顺）: 9V74, 7763，8370C，8272CL，8171M，E5-2673\n"
        echo "-------------------------CPU 情報---------------------------"
        echo "CPUの物理数  : $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPUコア数    : $(nproc)"
        echo -e "CPUモデル情報: $CPU_MODEL\n"
        echo "------------------------メモリ情報--------------------------"
        echo "メモリの詳細:"
        free -h
        echo ""
        echo "---------------------ハードディスク情報---------------------"
        # 兼容更多磁盘命名方式
        echo "ディスクデバイス数: $(lsblk -dn -o NAME | grep -E '^sd|^vd|^nvme' | wc -l)"
        df -hT
        echo ""
        echo "------------------サーバー最適化の実行結果------------------"
        if [[ "$CPU_MODEL" != *"EPYC 7763"* && "$CPU_MODEL" != *"EPYC 9V74"* ]]; then
          echo "❌ ハードウェア不適合、ジョブを停止します。"
          gh workflow run "${{ github.workflow }}" --ref "${{ github.ref_name }}"
          sleep 15
          gh run cancel ${{ github.run_id }}
          sleep 10
          exit 1
        fi
        echo "✅ ハードウェアチェック完了、実行を継続。"
        if [ "$FREE_SPACE" -lt 50 ]; then
          echo "⚠️ ストレージ不足、拡張プロセスを開始。"
          echo "needs_maximize=true" >> $GITHUB_OUTPUT
        else
          echo "✅ ストレージ容量正常、実行を継続。"
          echo "needs_maximize=false" >> $GITHUB_OUTPUT
        fi

    - name: Free Disk Space (ディスク空き容量の確保)
      if: steps.check_env.outputs.needs_maximize == 'true'
      uses: easimon/maximize-build-space@master
      with: 
        root-reserve-mb: 8192
        swap-size-mb: 1
        
    - name: Initialize Environment (環境の初期化)
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt -yqq update
        sudo -E apt -yqq install zip rename dos2unix libfuse-dev python3-netifaces libcrypt-dev libncurses5-dev #cargo
        sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        # rustup target add aarch64-unknown-linux-musl
        sudo timedatectl set-timezone "$TZ"
        sudo chown $USER:$GROUPS $GITHUB_WORKSPACE
        git config --global url."https://$ACCESS_TOKEN@github.com/0xACE8/".insteadOf "https://github.com/0xACE8/"
        git config --global core.compression 0

    - name: Clone Source Code (ソースコードのクローン)
      working-directory: ./
      run: |
        df -hT $PWD
        git clone --depth 1 $REPO_IMMORTALWRT_SOURCE_LINK -b $REPO_IMMORTALWRT_2512SS_HEAD openwrt
        # Remove China Mirrors (中国国内ミラーの削除)
        cd openwrt
        [ -f "scripts/projectsmirrors.json" ] && sed -i '/.cn\//d; /tencent/d; /aliyun/d' scripts/projectsmirrors.json
        [ -d "files" ] && rm -rf files
        # Add annawrt-packages Repo To Feeds ()
        ${{ secrets.ADD_FEEDS_OP2512 }}

    - name: Initialize Cache Hash (キャッシュハッシュの初期化)
      working-directory: ./openwrt
      run: |
        SHORT_HASH=$(md5sum feeds.conf.default | md5sum | cut -c1-7)
        echo "CACHE_HASH=${SHORT_HASH}" >> $GITHUB_ENV
        echo "✅ キャッシュハッシュの生成完了: ${SHORT_HASH}"

    - name: Cache Toolchain (ツールチェーンのキャッシュ)
      id: cache-toolchain
      uses: actions/cache@v4
      with:
        key: ${{ env.TARGET_CHIP }}-${{ env.SOURCE_CODE }}-${{ env.REPO_IMMORTALWRT_2410SS_TREE }}-${{ env.REPO_IMMORTALWRT_2512SS_HEAD }}-${{ env.CACHE_HASH }}-${{ env.IS_KEEPALIVE == 'true' && github.run_id || 'stable' }}
        restore-keys: |
          ${{ env.TARGET_CHIP }}-${{ env.SOURCE_CODE }}-${{ env.REPO_IMMORTALWRT_2410SS_TREE }}-${{ env.REPO_IMMORTALWRT_2512SS_HEAD }}-${{ env.CACHE_HASH }}-
        path: |
          openwrt/.cache
          openwrt/.ccache
          openwrt/staging_dir/host*
          openwrt/staging_dir/tool*
          openwrt/dl

    - name: Update & Install Feeds (フィードの更新とインストール)
      working-directory: ./openwrt
      run: |
        # Surgical Clean Go Cache (Goキャッシュの物理削除)
        [ -d "dl" ] && find dl -size 0 -exec rm -f {} +
        [ -d "dl" ] && rm -rf dl/go-mod-* 2>/dev/null || true
        ${{ secrets.RASPBERRYPI_3B_IMWRT2410SS_PATCHES }}
        # rtl88x2bu support
        git clone -b openwrt-25.12.0-rc4 https://github.com/mirobiala/rtl88x2bu-cl package/kernel/rtl88x2bu-cl
        ./scripts/feeds update -a
        rm -rf feeds/packages/lang/golang && git clone https://github.com/sbwml/packages_lang_golang -b 26.x feeds/packages/lang/golang
        ./scripts/feeds install -a

    - name: Load Custom Configuration (カスタム設定の読み込み)
      working-directory: ./openwrt
      id: loadconfig
      run: |
        set +x
        cat <<'EOF' > .config
        ${{ secrets.RASPBERRYPI_3B_IMWRT2512SS_PROFILE }}
        EOF
        echo "config done"
        ${{ secrets.REPO_IMMORTALWRT_2410SS_DIFF }}
        echo "diff done"
        ${{ secrets.ARGON_THEME_RPI }}
        echo "theme done"

    - name: Update Cache (キャッシュの更新)
      if: steps.cache-toolchain.outputs.cache-hit == 'true' || steps.cache-toolchain.outputs.cache-matched-key != ''
      working-directory: ./openwrt
      run: |
        if [ -d "staging_dir/host" ]; then
          find staging_dir -type d -name "stamp" -not -path "*target*" -exec touch {} + 2>/dev/null || true
          sed -i 's/ $(tool.*\/stamp-compile)//;' Makefile
          sed -i 's/ $(tool.*\/stamp-install)//;' Makefile
          mkdir -p tmp && echo "1" > tmp/.build
        fi

    - name: Restore Config Archive (設定アーカイブの復元)
      if: steps.loadconfig.outcome == 'success' && env.INPUT_RESTORE == 'true'
      working-directory: ./openwrt
      run: |
        ${{ secrets.RASPBERRYPI_3B_IMWRT2410SS_ARCHIVE }}
        echo "OUTPUT_FILE=diamondwrt-im25.12rc5-k6.12-bcm2710-raspberry-pi_3b-8g_tf-configured-sysupgrade" >> $GITHUB_ENV

    - name: Download Packages (パッケージのダウンロード)
      if: steps.loadconfig.outcome == 'success' && !cancelled()
      working-directory: ./openwrt
      id: package
      run: |
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        # make download -j8

    - name: Keepalive Cache Refresh (キャッシュ更新のマーク付け)
      if: env.IS_KEEPALIVE == 'true'
      run: |
        mkdir -p openwrt/.cache
        date -u +"%Y-%m-%dT%H:%M:%SZ" > openwrt/.cache/keepalive_timestamp
        echo "✅ キャッシュ更新のフラグ設定。フルビルドはスキップされました。"
        echo "ℹ️ フルビルドはスキップされ、メンテナンスモードで実行中です。"

    - name: Compile Firmware (ファームウェアのコンパイル)
      if: env.IS_KEEPALIVE != 'true'
      working-directory: ./openwrt
      id: compile
      env:
        export CARGO_PROFILE_RELEASE_OPT_LEVEL: "3"
        export CARGO_PROFILE_RELEASE_LTO: "true"
        export CARGO_PROFILE_RELEASE_CODEGEN_UNITS: "1"
        export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-C target-cpu=cortex-a53 -C target-feature=+crypto,+crc,+neon"
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Update Variables (変数の更新)
      if: steps.compile.outcome == 'success'
      run: |
        echo "OUTPUT_FILE=${OUTPUT_FILE}_${FILE_DATE}" >> $GITHUB_ENV

    - name: Organize Files (ファイルの整理)
      if: steps.compile.outcome == 'success'
      id: organize
      run: |
        cd openwrt/bin/targets/*/*
        ls | grep -v *.gz | xargs rm -rdf
        sha512sums ${{ secrets.ACCESS_SHA512SUM }} sha512sums *.gz
        ls | grep -v sha512sums* | xargs rm -rdf
        ${{ secrets.ACCESS_REPACKAGE }} ${{ env.OUTPUT_FILE }}.img.gz
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV

    - name: Upload to Artifacts (Artifactに保存)
      if: steps.organize.outcome == 'success' && env.INPUT_ARTIFACT == 'true'
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.OUTPUT_FILE }}
        path: ${{ env.FIRMWARE }}

    - name: Upload to Release (Releaseに公開)
      if: steps.compile.outcome == 'success' && env.INPUT_RELEASE == 'true'
      uses: softprops/action-gh-release@master
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        tag_name: ${{ env.FILE_DATE }}_${{ env.DEVICE_NAME }}_${{ env.REPO_IMMORTALWRT_2512SS_HEAD }}
        name: ${{ env.TARGET_CHIP }}_${{ env.DEVICE_NAME }}_${{ env.TARGET_DISK }}_${{ env.KERNEL_VERS }}_${{ env.FILE_DATE }}
        files: ${{ env.FIRMWARE }}/*
        body: |
          **本ファームウェアは、CPU「${{ env.TARGET_CHIP }}」搭載のモデル「${{ env.DEVICE_NAME }}」✅ ${{ env.TARGET_DISK }} ✅専用です。**
          ### 📒「${{ env.SOURCE_CODE }}」のソースコードを基にビルドされました。
          - 🖥️ 対応機種: 　${{ env.DEVICE_NAME }}
          - 💿 容量仕様: 　${{ env.TARGET_DISK }}
          - 🐧 カーネル: 　${{ env.KERNEL_VERS }}
          - 👤 ソース名: 　${{ env.SOURCE_CODE }}
          - 🌲 ソース元: 　${{ env.REPO_IMMORTALWRT_2410SS_TREE }}
          - 🌿 ブランチ: 　${{ env.REPO_IMMORTALWRT_2512SS_HEAD }}
          - 🔗 管理ＩＰ: 　192.168.***.1 または ${{ env.SOURCE_CODE }}.lan
          - 🛡️ 初期パス: 　********
          ### ⚠️ 免責事項 ⚠️
          - ‼️ **本ファームウェアは、個人利用を目的とした非公式のカスタマイズ版です。**
          - ⛔️ **強制フラッシュ等でデバイスが破損した場合、本リポジトリは一切の責任を負いません。自己責任で使用してください。**

    - name: Calculate Duration (実行時間の計算)
      if: always() && env.INPUT_NOTIFY == 'true' && env.IS_KEEPALIVE != 'true'
      run: |
        END_TIME=$(date +%s)
        START_TIME=${{ env.START_TIME }}
        TOTAL_SECONDS=$((END_TIME - START_TIME))
        H=$((TOTAL_SECONDS / 3600))
        M=$(((TOTAL_SECONDS % 3600) / 60))
        S=$((TOTAL_SECONDS % 60))
        echo "DURATION=$(printf "%02d:%02d:%02d" $H $M $S)" >> $GITHUB_ENV

    - name: Final Report & TG Notify (総合ステータス通知)
      if: always() && env.INPUT_NOTIFY == 'true' && env.IS_KEEPALIVE != 'true'
      run: |
        get_stat() { [ "$1" == "true" ] && echo "✅" || echo "⏺️"; }
        
        [ "${{ steps.compile.outcome }}" == "success" ] && BUILD_STAT="✅ビルドが正常に完了しました！✅" || BUILD_STAT="❌ ビルドが失敗しました！ ❌"
        
        STAT_LIST="•⚙️%20配置复元:　%20　%20　$(get_stat "${{ github.event.inputs.restore_config }}")%0A"
        STAT_LIST="${STAT_LIST}•💾%20构建成果:　%20　%20　$(get_stat "${{ github.event.inputs.upload_firmware }}")%0A"
        STAT_LIST="${STAT_LIST}•🚀%20公开配信:　%20　%20　$(get_stat "${{ github.event.inputs.upload_release }}")%0A"
        STAT_LIST="${STAT_LIST}•🧹%20缓存清理:　%20　%20　$(get_stat "${{ github.event.inputs.clean_cache }}")%0A"

        MSG="${BUILD_STAT}%0A"
        MSG="${MSG}%0A＝＝＝＝＝  基 本 情 報 ＝＝＝＝＝＝"
        MSG="${MSG}%0A•🖥️%20対応機種:%0A　%20　%20　${DEVICE_NAME}"
        MSG="${MSG}%0A•💿%20容量仕様:%0A　%20　%20　${TARGET_DISK}"
        MSG="${MSG}%0A•🐧%20カーネル:%0A　%20　%20　${KERNEL_VERS}"
        MSG="${MSG}%0A•👤%20ソース名:%0A　%20　%20　${SOURCE_CODE}"
        MSG="${MSG}%0A•🌲%20ソース元:%0A　%20　%20　${REPO_IMMORTALWRT_2410SS_TREE}"
        MSG="${MSG}%0A•🌿%20ブランチ:%0A　%20　%20　${REPO_IMMORTALWRT_2512SS_HEAD}%0A"

        MSG="${MSG}%0A＝＝＝＝＝ 状 態 一 覧 ＝＝＝＝＝＝%0A${STAT_LIST}%0A"
        MSG="${MSG}＝＝＝＝＝ 結 果 情 報 ＝＝＝＝＝＝%0A"
        MSG="${MSG}•⏱️%20実行時間:　%20　%20　${{ env.DURATION }}%0A"
        
        if [ "${{ steps.compile.outcome }}" == "success" ]; then
          MSG="${MSG}•📦%20ファイル:%0A　%20　%20　${OUTPUT_FILE}%0A"
        else
          MSG="${MSG}•❌%20失敗時刻:　%20　%20　$(date +'%Y-%m-%d %H:%M')%0A"
        fi

        MSG="${MSG}%0A＝＝＝ ＝＝＝ ＝＝＝ ＝＝＝ ＝＝＝ "
        
        curl -s -o /dev/null -X GET "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_KEY }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="$(echo "$MSG" | sed 's/ /%20/g')"
  
    - name: Delete Old Releases (古いリリースの削除)
      if: steps.compile.outcome == 'success' && env.INPUT_RELEASE == 'true'
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 2
        delete_tags: true
        delete_tag_pattern: "${{ env.DEVICE_NAME }}_${{ env.REPO_IMMORTALWRT_2512SS_HEAD }}" 
    
    
